{
 "title": "App Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total Request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_duration_bucket{http_server_name=\"products\", http_status_code=~\"2..\", le=\"+Inf\"}[5m])",
     "legendFormat": "2xx"
    },
    {
     "expr": "rate(http_server_duration_bucket{http_server_name=\"products\", http_status_code=~\"4..\", le=\"+Inf\"}[5m])",
     "legendFormat": "4xx"
    },
    {
     "expr": "rate(http_server_duration_bucket{http_server_name=\"products\", http_status_code=~\"5..\", le=\"+Inf\"}[5m])",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "P95 Request Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{}[5m])) by(le, job))",
     "legendFormat": "all"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{http_status_code=\"200\"}[5m])) by(le, job))",
     "legendFormat": "200"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{http_status_code!=\"200\"}[5m])) by(le, job))",
     "legendFormat": "!=200"
    }
   ]
  },
  {
   "title": "SLO Latency Percentile 200ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_bucket{http_server_name=\"products\", le=\"200\"}[5m])) by (job, http_server_name)\n/\nsum(rate(http_server_duration_count{http_server_name=\"products\"}[5m])) by (job, http_server_name)",
     "legendFormat": "{{http_server_name}}"
    }
   ]
  }
 ]
}